[package]
name = "wasmgame"
version = "0.1.0"
authors = ["Ilya fanyShu <ilyashvy@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
stdweb = "0.4.8"
serde = "1.0.71"
serde_derive = "1.0.71"
lazy_static = "1.1.0"